CC='clang' CXX='clang++' \
cmake -S llvm -B build -G Ninja \
-DCMAKE_C_COMPILER=clang \
-DCMAKE_CXX_COMPILER=clang++ \
-DLLVM_ENABLE_PROJECTS="clang;lld" \
-DLLVM_ENABLE_RUNTIMES="libc" \
-DLLVM_RUNTIME_TARGETS="v810-unknown-vb" \
-DLLVM_INCLUDE_TESTS=OFF \
-DRUNTIMES_v810-unknown-vb_LIBCXX_ENABLE_LOCALIZATION=NO \
-DRUNTIMES_v810-unknown-vb_LIBCXX_ENABLE_THREADS=NO \
-DRUNTIMES_v810-unknown-vb_LIBCXXABI_ENABLE_THREADS=NO \
-DCMAKE_BUILD_TYPE=Release \
-DLLVM_TARGETS_TO_BUILD="Sparc;V810;X86"